name: demo_azure
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - streamlit-chat
   - streamlit
   - aiohttp
   - aiosignal
   - altair
   - asttokens
   - async-timeout
   - attrs
   - azure-core
   - azure-storage-blob
   - azure-storage-file-datalake
   - backcall
   - blinker
   - cachetools
   - certifi
   - cffi
   - charset-normalizer
   - click
   - comm
   - cryptography
   - dataclasses-json
   - debugpy
   - decorator
   - dnspython
   - executing
   - frozenlist
   - gitdb
   - gitpython
   - greenlet
   - idna
   - importlib-metadata
   - ipykernel
   - ipython
   - isodate
   - jedi
   - jinja2
   - jsonschema
   - jupyter-client
   - jupyter-core
   - langchain
   - langchainplus-sdk
   - loguru
   - markdown-it-py
   - markupsafe 
   - marshmallow
   - marshmallow-enum
   - matplotlib-inline
   - mdurl
   - multidict
   - mypy-extensions
   - nest-asyncio
   - numexpr
   - numpy 
   - openai
   - openapi-schema-pydantic
   - packaging
   - pandas
   - parso
   - pexpect
   - pickleshare
   - pillow 
   - pinecone-client
   - platformdirs
   - prompt-toolkit 
   - protobuf
   - psutil
   - ptyprocess 
   - pure-eval
   - pyarrow 
   - pycparser
   - pydantic
   - pydeck
   - pygments
   - pympler
   - pyrsistent
   - python-dateutil
   - pytz 
   - pytz-deprecation-shim
   - pyyaml
   - pyzmq 
   - requests 
   - rich
   - six 
   - smmap 
   - sqlalchemy 
   - stack-data 
   - tenacity
   - toml
   - toolz
   - tiktoken
   - tornado
   - tqdm
   - traitlets
   - typing-inspect
   - typing-extensions
   - tzdata
   - tzlocal 
   - urllib3 
   - validators 
   - watchdog 
   - wcwidth
   - yarl 
   - zipp 
   - notebook 
   - llama-index 
   - docx2txt